trigger:
    branches:
      include:
      - main

pool:
    name: 'NexusPrivateAgents'
    vmImage: 'ubuntu-latest'

variables:
  GitVersion.SemVer: 'undefined'
  System.Debug: true

stages:
  - stage: security_checker
    displayName: 'Sonar Scan'
    jobs:
      - job: Analyze
        continueOnError: true
        steps:
          - template: sonar_qube_analyze.yml
            parameters:
              semVer: $(Build.BuildNumber)
              sonar: true
              SProjectKey: nexus-tf
              
  - stage: PreReqs
    jobs:
    - job: GitVersion
      steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '3.x'

        - task: gitversion/setup@0
          displayName: Install GitVersion
          inputs:
            versionSpec: '5.x'

        - task: gitversion/execute@0
          displayName: Calculate SemVer
          inputs:
            name: Version
            useConfigFile: true
            updateAssemblyInfo: false
            configFilePath: 'GitVersion.yml'

        - script: echo '##vso[build.updatebuildnumber]Nexus-Terraform-$(GitVersion.SemVer)'
          displayName: 'Set Build Number to Semantic Version'

##########################################################################################################################
  - template: tf-plan.yml
    parameters:
      environment: ops
      location: uksouth
      dependsOn: PreReqs
      workingDirectory: '/ops'
  - template: tf-apply.yml
    parameters:
      environment: ops
      location: uksouth
      dependsOn: Terraform_Plan_Nexus_ops_uksouth
      workingDirectory: '/ops'

  - template: ops-aks-crd-provisioning.yml
    parameters:
      environment: prd
      dependsOn: 'Terraform_Apply_Nexus_ops_uksouth'
      location: uksouth
      locationshortcode: uks
      aksumiclientid: '1a43ddd4-7681-4468-8f78-9c226e5cc139'
##########################################################################################################################   
  - template: tf-plan.yml
    parameters:
      environment: dev
      location: uksouth
      dependsOn: Terraform_Apply_Nexus_ops_uksouth
      workingDirectory: '/main'
  - template: tf-apply.yml
    parameters:
      environment: dev
      location: uksouth
      dependsOn: Terraform_Plan_Nexus_dev_uksouth
      workingDirectory: '/main'

  - template: tf-plan.yml
    parameters:
      environment: dev
      location: global
      dependsOn: Terraform_Apply_Nexus_dev_uksouth
      workingDirectory: '/global'
  - template: tf-apply.yml
    parameters:
      environment: dev
      location: global
      dependsOn: Terraform_Plan_Nexus_dev_global
      workingDirectory: '/global'

  - template: aks-crd-provisioning.yml
    parameters:
      environment: dev
      dependsOn: 'Terraform_Apply_Nexus_dev_uksouth'
      location: uksouth
      locationshortcode: uks
      aksumiclientid: 'fe40f3f7-b5d1-461b-bde9-eaa94cd54aed'
##########################################################################################################################   
  - template: tf-plan.yml
    parameters:
      environment: qa
      location: uksouth
      dependsOn: Terraform_Apply_Nexus_ops_uksouth
      workingDirectory: '/main'
  - template: tf-apply.yml
    parameters:
      environment: qa
      location: uksouth
      dependsOn: Terraform_Plan_Nexus_qa_uksouth
      workingDirectory: '/main'

  - template: tf-plan.yml
    parameters:
      environment: qa
      location: global
      dependsOn: Terraform_Apply_Nexus_qa_uksouth
      workingDirectory: '/global'
  - template: tf-apply.yml
    parameters:
      environment: qa
      location: global
      dependsOn: Terraform_Plan_Nexus_qa_global
      workingDirectory: '/global'

  - template: aks-crd-provisioning.yml
    parameters:
      environment: qa
      dependsOn: 'Terraform_Apply_Nexus_qa_uksouth'
      location: uksouth
      locationshortcode: uks
      aksumiclientid: 'ac2791c6-a8ce-41be-aabd-dde1b045193c'
##########################################################################################################################   
  - template: tf-plan.yml
    parameters:
      environment: sit
      location: uksouth
      dependsOn: Terraform_Apply_Nexus_ops_uksouth
      workingDirectory: '/main'
  - template: tf-apply.yml
    parameters:
      environment: sit
      location: uksouth
      dependsOn: Terraform_Plan_Nexus_sit_uksouth
      workingDirectory: '/main'

  - template: tf-plan.yml
    parameters:
      environment: sit
      location: global
      dependsOn: Terraform_Apply_Nexus_sit_uksouth
      workingDirectory: '/global'
  - template: tf-apply.yml
    parameters:
      environment: sit
      location: global
      dependsOn: Terraform_Plan_Nexus_sit_global
      workingDirectory: '/global'

  - template: aks-crd-provisioning.yml
    parameters:
      environment: sit
      dependsOn: 'Terraform_Apply_Nexus_sit_uksouth'
      location: uksouth
      locationshortcode: uks
      aksumiclientid: '9bc704fc-b9ed-4d2a-a42b-0ad732000b14'
##########################################################################################################################   
  - template: tf-plan.yml
    parameters:
      environment: prd
      location: uksouth
      dependsOn: Terraform_Apply_Nexus_ops_uksouth
      workingDirectory: '/main'
  - template: tf-apply.yml
    parameters:
      environment: prd
      location: uksouth
      dependsOn: Terraform_Plan_Nexus_prd_uksouth
      workingDirectory: '/main'

  - template: tf-plan.yml
    parameters:
      environment: prd
      location: global
      dependsOn: Terraform_Apply_Nexus_prd_uksouth
      workingDirectory: '/global'
  - template: tf-apply.yml
    parameters:
      environment: prd
      location: global
      dependsOn: Terraform_Plan_Nexus_prd_global
      workingDirectory: '/global'

  - template: aks-crd-provisioning.yml
    parameters:
      environment: prd
      dependsOn: 'Terraform_Apply_Nexus_prd_uksouth'
      location: uksouth
      locationshortcode: uks
      aksumiclientid: 'c709e449-3640-437d-93c1-5690b4f7f326