name: "Start and Stop Vyed Applications-$(Build.QueuedTime:yyyyMMdd-HHmmss)"
appendCommitMessageToRunName: false 

trigger: none

schedules:
  - cron: "0 6 * * Mon-Fri"
    displayName: "Start WebApp at 7 AM (Mon-Fri)"
    branches:
      include:
        - Development-Dileep
    always: true
    
  - cron: "0 18 * * Mon-Fri"
    displayName: "Stop WebApp at 7 PM (Mon-Fri)"
    branches:
      include:
        - Development-Dileep
    always: true

stages:
- stage: dev
  displayName: 'Start and Stop Dev Environment'
  variables:
  - group: s148-vyed-dev
  jobs:
  - job: Dev_Webapp
    steps:
    - task: AzureCLI@2
      displayName: 'Powershell task'
      inputs:
        azureSubscription: 's148d.azdo-deployment-dfe-gov'
        scriptType: 'pscore'
        scriptLocation: 'scriptPath'
        ScriptPath: $(Build.SourcesDirectory)/scripts/s148VYEDAutoStartStopApp.ps1
        arguments: '-subscriptionId "$(devSubscriptionId)" -resourceGroupName "$(devResourceGroupName)" -webAppNames @("$(devAdminWebApp)", "$(devPubWebApp)") -functionAppName "$(devFunctionAppName)"'

- stage: test
  displayName: 'Start and Stop Test Environment'
  variables:
  - group: s148-vyed-test
  jobs:
  - job: Test_Webapp
    steps:
    - task: AzureCLI@2
      displayName: 'Powershell task'
      inputs:
        azureSubscription: 's148t.azdo-deployment-dfe-gov'
        scriptType: 'pscore'
        scriptLocation: 'scriptPath'
        ScriptPath: $(Build.SourcesDirectory)/scripts/s148VYEDAutoStartStopApp.ps1
        arguments: '-subscriptionId "$(testSubscriptionId)" -resourceGroupName "$(testResourceGroupName)" -webAppNames @("$(testAdminWebApp)", "$(testPubWebApp)") -functionAppName "$(testFunctionAppName)"'

- stage: Uat
  displayName: 'Start and Stop Uat Environment'
  variables:
  - group: s148-vyed-uat
  jobs:
  - job: Uat_Webapp
    steps:
    - task: AzureCLI@2
      displayName: 'Powershell task'
      inputs:
        azureSubscription: 's148t.azdo-deployment-dfe-gov'
        scriptType: 'pscore'
        scriptLocation: 'scriptPath'
        ScriptPath: $(Build.SourcesDirectory)/scripts/s148VYEDAutoStartStopApp.ps1
        arguments: '-subscriptionId "$(uatSubscriptionId)" -resourceGroupName "$(uatResourceGroupName)" -webAppNames @("$(uatAdminWebApp)", "$(uatPubWebApp)") -functionAppName "$(uatFunctionAppName)"'

- stage: Pre_prod
  displayName: 'Start and Stop Pre_prod Environment'
  variables:
  - group: s148-vyed-pre-prod
  jobs:
  - job: Pre_prod_Webapp
    steps:
    - task: AzureCLI@2
      displayName: 'Powershell task'
      inputs:
        azureSubscription: 's148p.azdo-deployment-dfe-gov'
        scriptType: 'pscore'
        scriptLocation: 'scriptPath'
        ScriptPath: $(Build.SourcesDirectory)/scripts/s148VYEDAutoStartStopApp.ps1
        arguments: '-subscriptionId "$(preprodSubscriptionId)" -resourceGroupName "$(preprodResourceGroupName)" -webAppNames @("$(preprodAdminWebApp)", "$(preprodPubWebApp)") -functionAppName "$(preprodFunctionAppName)"'