
trigger: none

schedules:
  - cron: "0 7 * * Mon-Fri"
    displayName: "Start WebApp at 7 AM (Mon-Fri)"
    branches:
      include:
        - main
    always: true
    
  - cron: "0 19 * * Mon-Fri"
    displayName: "Stop WebApp at 7 PM (Mon-Fri)"
    branches:
      include:
        - main
    always: true

stages:
- stage: dev
  displayName: 'Start and Stop Dev Environment'
  variables:
  - name: subscriptionId
    value: 'your-subscription-id'
  - name: resourceGroupName
    value: 'YourResourceGroupName'
  - name: webAppNames
    value: |
      WebApp1
      WebApp2
  - name: functionAppName
    value: 'YourFunctionAppName'
  jobs:
  - job: Dev_Webapp
    steps:
    - task: AzurePowerShell@5
      displayName: 'Powershell task'
      inputs:
        azureSubscription: '${{ parameters.ServiceConn }}'
        ScriptType: 'FilePath'
        ScriptPath: 'webapp.ps1'
        ScriptArguments: '-subscriptionId $(subscriptionId) -resourceGroupName $(resourceGroupName) -webAppNames $(webAppNames) -functionAppName $(functionAppName)'
        azurePowerShellVersion: 'LatestVersion'
        pwsh: true

- stage: test
  displayName: 'Start and Stop test Environment'
  jobs:
  - job: test_Webapp
    variables:
    - name: subscriptionId
      value: 'your-test-subscription-id'
    - name: resourceGroupName
      value: 'YourtestResourceGroupName'
    - name: webAppNames
      value: |
        testWebApp1
        testWebApp2
    - name: functionAppName
      value: 'YourFunctionAppName'
    steps:
    - task: AzurePowerShell@5
      displayName: 'Powershell task'
      inputs:
        azureSubscription: '${{ parameters.ServiceConn }}'
        ScriptType: 'FilePath'
        ScriptPath: 'webapp.ps1'
        ScriptArguments: '-subscriptionId $(subscriptionId) -resourceGroupName $(resourceGroupName) -webAppNames $(webAppNames) -functionAppName $(functionAppName)'
        azurePowerShellVersion: 'LatestVersion'
        pwsh: true

  - job: uat_Webapp
    variables:
    - name: subscriptionId
      value: 'your-uat-subscription-id'
    - name: resourceGroupName
      value: 'YouruatResourceGroupName'
    - name: webAppNames
      value: |
        uatWebApp1
        uatWebApp2
    - name: functionAppName
      value: 'YourFunctionAppName'
    steps:
    - task: AzurePowerShell@5
      displayName: 'Powershell task'
      inputs:
        azureSubscription: '${{ parameters.ServiceConn }}'
        ScriptType: 'FilePath'
        ScriptPath: 'webapp.ps1'
        ScriptArguments: '-subscriptionId $(subscriptionId) -resourceGroupName $(resourceGroupName) -webAppNames $(webAppNames) -functionAppName $(functionAppName)'
        azurePowerShellVersion: 'LatestVersion'
        pwsh: true

- stage: prod
  displayName: 'Start and Stop prod Environment'
  jobs:
  - job: preprod_Webapp
    variables:
    - name: subscriptionId
      value: 'your-preprod-subscription-id'
    - name: resourceGroupName
      value: 'YourPreProdResourceGroupName'
    - name: webAppNames
      value: |
        PreProdWebApp1
        PreProdWebApp2
    - name: functionAppName
      value: 'YourFunctionAppName'
    steps:
    - task: AzurePowerShell@5
      displayName: 'Powershell task'
      inputs:
        azureSubscription: '${{ parameters.ServiceConn }}'
        ScriptType: 'FilePath'
        ScriptPath: 'webapp.ps1'
        ScriptArguments: '-subscriptionId $(subscriptionId) -resourceGroupName $(resourceGroupName) -webAppNames $(webAppNames) -functionAppName $(functionAppName)'
        azurePowerShellVersion: 'LatestVersion'
        pwsh: true

  - job: prod_Webapp
    variables:
    - name: subscriptionId
      value: 'your-prod-subscription-id'
    - name: resourceGroupName
      value: 'YourProdResourceGroupName'
    - name: webAppNames
      value: |
        ProdWebApp1
        ProdWebApp2
    - name: functionAppName
      value: 'YourFunctionAppName'
    steps:
    - task: AzurePowerShell@5
      displayName: 'Powershell task'
      inputs:
        azureSubscription: '${{ parameters.ServiceConn }}'
        ScriptType: 'FilePath'
        ScriptPath: 'webapp.ps1'
        ScriptArguments: '-subscriptionId $(subscriptionId) -resourceGroupName $(resourceGroupName) -webAppNames $(webAppNames) -functionAppName $(functionAppName)'
        azurePowerShellVersion: 'LatestVersion'
        pwsh: true
