trigger: none

schedules:
  - cron: "0 7 * * Mon-Fri"
    displayName: "Start WebApp at 7 AM (Mon-Fri)"
    branches:
      include:
        - main
    always: true
    
  - cron: "0 19 * * Mon-Fri"
    displayName: "Stop WebApp at 7 PM (Mon-Fri)"
    branches:
      include:
        - main
    always: true

stages:
- stage: dev
  displayName: 'Start and Stop Dev Environment'
  variables:
  - group: dev
  - name: webAppNames
    value: |
      WebApp1
      WebApp2
  jobs:
  - job: Dev_Webapp
    displayname: 'Start or Stop Dev Webapp
    steps:
     - task: AzurePowerShell@5
      displayName: 'Powershell task'
      inputs:
        azureSubscription: '${{ parameters.ServiceConn }}'
        ScriptType: 'FilePath'
        ScriptPath: 'webapp.ps1'
        ScriptArguments: '-subscriptionId $(subscriptionId) -resourceGroupName $(resourceGroupName) -webAppNames $(webAppNames)'
        azurePowerShellVersion: 'LatestVersion'
        pwsh: true

- stage: prod
  displayName: 'Start and Stop prod Environment'
  variables:
  - group: prod
  - name: webAppNames
    value: |
      WebApp1
      WebApp2
  jobs:
  - job: prod_Webapp
    displayname: 'Start or Stop prod Webapp
    steps:
     - task: AzurePowerShell@5
      displayName: 'Powershell task'
      inputs:
        azureSubscription: '${{ parameters.ServiceConn }}'
        ScriptType: 'FilePath'
        ScriptPath: 'webapp.ps1'
        ScriptArguments: '-subscriptionId $(subscriptionId) -resourceGroupName $(resourceGroupName) -webAppNames $(webAppNames)'
        azurePowerShellVersion: 'LatestVersion'
        pwsh: true
