trigger:
- main

variables:
  resourceGroupName: 'your-existing-rg-name'
  factoryName: 'myADFFactory'
  location: 'eastus'    

stages:
- stage: ValidateBicep
  displayName: 'Validate ADF Deployment with What-If'
  jobs:
  - job: WhatIf
    displayName: 'Run What-If Analysis'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'YourAzureServiceConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Running What-If Deployment for Bicep..."
          az deployment sub what-if \
            --location $(location) \
            --template-file main.bicep \
            --parameters resourceGroupName=$(resourceGroupName) factoryName=$(factoryName) location=$(location) resourceTags='{"Account Code":"Z00DS000A","Analysis Code":"2431104","Cost Centre":"10420751","Environment":"Dev","Owner":"Fowler, Greg","Parent Business":"Business Intelligence","Portfolio":"Education and Skills Funding Agency","Product":"View Your Education Data","Service":"Business Intelligence","Service Offering":"View Your Education Data"}'
      displayName: 'Bicep What-If Analysis'

- stage: DeployADF
  displayName: 'Deploy ADF After Approval'
  dependsOn: ValidateBicep
  condition: succeeded()
  jobs:
  - deployment: DeployADF
    displayName: 'Execute Deployment to Resource Group'
    environment: 'Production'   # we need to Set up this environment in DevOps UI
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'YourAzureServiceConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Deploying Azure Data Factory..."
                az deployment sub create \
                 --location $(location) \
                 --template-file main.bicep \
                 --parameters resourceGroupName=$(resourceGroupName) factoryName=$(factoryName) location=$(location) resourceTags='{"Account Code":"Z00DS000A","Analysis Code":"2431104","Cost Centre":"10420751","Environment":"Dev","Owner":"Fowler, Greg","Parent Business":"Business Intelligence","Portfolio":"Education and Skills Funding Agency","Product":"View Your Education Data","Service":"Business Intelligence","Service Offering":"View Your Education Data"}'
            displayName: 'Deploy ADF using Bicep'
