trigger: none
#appendCommitMessageToRunName: false

stages:
  - stage: ValidateADFResourcesBicepDev
    displayName: 'Validate ADF Resources Deployment Dev'
    variables:
      - group: s148-vyed-dev
    jobs:
      - job: WhatIf_Dev
        displayName: 'Run What-If Analysis'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            displayName: 'Bicep What-If Analysis'
            inputs:
              azureSubscription: 's148d.azdo-deployment-dfe-gov'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Running What-If Deployment for ADF Resources..."
                az deployment group what-if \
                  --resource-group $(devDataFactoryRGName) \
                  --template-file adfresources/main.bicep \
                  --parameters factoryName=$(devDataFactoryName) \
                               storageAccountName=$(storageAccountName) \
                               containerName=$(containerName)

  - stage: DeployADFResourcesDev
    displayName: 'Deploy ADF Resources Dev'
    dependsOn: ValidateADFResourcesBicepDev
    condition: succeeded()
    variables:
      - group: s148-vyed-dev
    jobs:
      - deployment: DeployADFResources
        displayName: 'Execute ADF Resources Deployment to Dev'
        environment: 'deploys148adf'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - script: |
                    echo "Removing existing Azure CLI..."
                    sudo apt-get remove -y azure-cli

                    echo "Adding Microsoft package repo..."
                    curl -sL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
                    AZ_REPO=$(lsb_release -cs)
                    echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list

                    echo "Installing Azure CLI 2.71.0..."
                    sudo apt-get update
                    sudo apt-get install -y azure-cli=2.71.0-1~${AZ_REPO}

                    echo "Azure CLI version after downgrade:"
                    az --version
                  displayName: 'Downgrade Azure CLI to 2.71.0'

                - task: AzureCLI@2
                  displayName: 'Deploy ADF Resources using Bicep'
                  inputs:
                    azureSubscription: 's148d.azdo-deployment-dfe-gov'
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      echo "Deploying ADF Resources..."
                      az deployment group create \
                        --resource-group $(devDataFactoryRGName) \
                        --template-file adfresources/main.bicep \
                        --parameters factoryName=$(devDataFactoryName) \
                                     storageAccountName=$(storageAccountName) \
                                     containerName=$(containerName)
