---
- name: Create a directory on the remote server
  hosts: all  # Define the target hosts (use a specific group or 'all' for all hosts in the inventory)
  become: yes  # Use become if you need to perform the task with sudo privileges
  tasks:
    - name: create a directory structure 
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /Ent/inventory/in/account
        - /Ent/inventory/in/account/subdir1
        - /Ent/inventory/in/account/subdir2
        - /Ent/inventory/in/account/subdir1/subsubdir1
